/* mtbbergamo TRACKS */

var TRACKS = [
{ zone: 'maresana', name: '532', kind: 'down', file: 'M_532_REC.gpx' },
{ zone: 'maresana', name: '604', kind: 'down', file: 'M_604_REC.gpx', link: '2018/11/604' },
{ zone: 'maresana', name: 'Bruna', kind: 'down', file: 'M_Bruna.gpx', link: '2018/11/bruna' },
{ zone: 'maresana', name: 'FarWest', kind: 'down', file: 'M_FarWest_REC.gpx', link: '2018/11/farwest' },
{ zone: 'maresana', name: '401 / Filoncino', kind: 'down', file: 'M_Filoncino_REC.gpx', link: '2018/11/401-filoncino' },
{ zone: 'maresana', name: 'Filone Easy', kind: 'down', file: 'M_FiloneEasy_REC.gpx', link: '2018/11/filone-easy' },
{ zone: 'maresana', name: '533 / Filone', kind: 'down', file: 'M_Filone_REC.gpx', link:'2018/11/533-filone' },
{ zone: 'maresana', name: '533 / Illegale / Veloce', kind: 'down', file: 'M_Illegale_REC.gpx', link: '2018/11/533-illegale' },
{ zone: 'maresana', name: 'Rosciano', kind: 'down', file: 'M_Rosciano_REC.gpx', link: '2018/11/rosciano' },
{ zone: 'maresana', name: 'Salita da Ranica', kind: 'up', file: 'M_SalitaRanica_REC.gpx', link: '2018/11/salite-maresana' },
{ zone: 'maresana', name: 'Salita da Ponteranica', kind: 'up', file: 'M_SalitaPonteranica_REC.gpx', link: '2018/11/salite-maresana' },
{ zone: 'maresana', name: '402 / San Rocco', kind: 'down', file: 'M_SanRocco_REC.gpx', link: '2018/11/402-san-rocco' },
{ zone: 'maresana', name: '409 / Tornantini', kind: 'down', file: 'M_Tornantini_REC.gpx', link: '2018/11/tornantini' },
{ zone: 'maresana', name: 'Legnaia', kind: 'down', file: 'M_Legnaia_REC.gpx', link: '2018/11/legnaia' },
{ zone: 'maresana', name: 'Luca West', kind: 'down', file: 'M_LucaWest_REC.gpx', link: '2018/11/lucawest' },
{ zone: 'imagna', name: 'Brumano, Passo Porta, Rota, Selino', kind: 'down', file: 'I_BrumanoPassoPortaRotaSelino.gpx', link: '2018/12/brumano-passo-porta-rota-selino' },
{ zone: 'imagna', name: 'Ceresola, Roccoli Passata, Partigiano, Costa Cavallina, Clanezzo', kind: 'down', file: 'I_CeresolaRoccoliPassataPartigianoCostaCavallinaClanezzo.gpx' },
{ zone: 'imagna', name: 'Palio, Canti, Tre Faggi', kind: 'down', file: 'I_PalioCantiTreFaggi.gpx', link: '2018/12/palio-canti-tre-faggi' },
{ zone: 'imagna', name: 'Palio, Rifugio Resegone, Passo Porta, 575, Valsecca', kind: 'down', file: 'I_PalioRifugioResegonePassoPorta575Valsecca.gpx' },
{ zone: 'imagna', name: 'Tre Faggi, 580, Locatello, Selino', kind: 'down', file: 'I_TreFaggi580LocatelloSelino.gpx' },
{ zone: 'imagna', name: 'Tre Faggi, Corna, Blello, Selino Alto, Ponte Pietra', kind: 'down', file: 'I_TreFaggiCornaBlelloSelinoAltoPontePietra.gpx', link: '2018/11/tra-faggi-corna-blello-selino-alto' },
{ zone: 'imagna', name: 'Salita dalla Sbarra di Brumano al Palio', kind: 'up', file: 'I_SalitaSbarraPalio_REC.gpx', link: '2018/12/salite-imagna' },
{ zone: 'imagna', name: 'Salita da Selino a Fuipiano e ai Tre Faggi', kind: 'up', file: 'I_SalitaSelinoFuipianoTreFaggi_REC.gpx', link: '2018/12/salite-imagna' },
{ zone: 'imagna', name: 'Salita da Almenno a Costa Imagna e Valcava', kind: 'up', file: 'I_SalitaAlmenoBedulitaCostaValcava.gpx', link: '2018/12/salite-imagna' },
{ zone: 'imagna', name: 'Trasferimento da Valsecca a Rota Imagna e a Locatello', kind: 'up', file: 'I_ValseccaRotaLocatello_REC.gpx', link: '2018/12/salite-imagna' },
{ zone: 'imagna', name: 'Ciclabile Valle Imagna', kind: 'up', file: 'I_CiclabileValleImagna.gpx', link: '2018/12/salite-imagna' },
{ zone: 'imagna, valcava', name: 'Forcella Alta, 573, Mazzoleni, Selino', kind: 'down', file: 'I_ForcellaAlta573CostaMazzoleniSelino.gpx' },
{ zone: 'imagna, valcava', name: 'Forcella Alta, 574, Valsecca, Selino', kind: 'down', file: 'I_ForcellaAlta574ValseccaSelino.gpx' },
{ zone: 'imagna, valcava', name: 'Linzone Roncola Alta, Amagno', kind: 'down', file: 'I_LinzoneRoncolaAltaAmagno.gpx' },
{ zone: 'imagna, valcava', name: 'Linzone Roncola, Barlino', kind: 'down', file: 'I_LinzoneRoncolaBarlino.gpx', link: '2018/11/linzone-roncola-barlino' },
{ zone: 'martino, imagna, valcava', name: 'Salita da Valcava al Linzone', kind: 'up', file: 'N_ValcavaLinzone_REC.gpx' },
{ zone: 'martino, valcava', name: 'Linzone, Monte Piacca, Baia, Spino, Burligo', kind: 'down', file: 'N_LinzonePiaccaBaitaSpinoBurligo_REC.gpx', link: '2018/11/linzone-monte-piacca-baita-burligo' },
{ zone: 'martino, valcava', name: 'Linzone, Monte Piacca, Spino, Ciacallo, Burligo', kind: 'down', file: 'N_LinzonePiaccaSpinoCiacallo807Burligo_REC.gpx', link: '2018/11/linzone-monte-piacca-baita-burligo' },
{ zone: 'martino, valcava', name: 'Valcava, Coldara, Colle Pedrino, Opreno, Burligo', kind: 'down', file: 'N_ValcavaColdaraPedrinoOprenoBurligo.gpx' },
{ zone: 'canto', name: 'Genestaro', kind: 'down', file: 'C_Genestaro_REC.gpx' },
{ zone: 'canto', name: 'Guendalina', kind: 'down', file: 'C_Guendalina_REC.gpx' } ,
{ zone: 'canto', name: 'Kompressor', kind: 'down', file: 'C_Kompressor_REC.gpx' },
{ zone: 'canto', name: 'Pietra Sant Albero', kind: 'down', file: 'C_PietraSAlbero_REC.gpx' },
{ zone: 'canto', name: 'Salita da Sotto il Monte', kind: 'up', file: 'C_SalitaSottoIlMonte_REC.gpx' },
{ zone: 'canto', name: 'Salita al Monte Canto', kind: 'up', file: 'C_SalitaMonteCanto_REC.gpx' },
{ zone: 'canto', name: 'Salita da Pontida', kind: 'up', file: 'C_SalitaPontida_REC.gpx' },
{ zone: 'canto', name: 'Salita da Ambivere', kind: 'up', file: 'C_SalitaAmbivere_REC.gpx' },
{ zone: 'canto', name: 'Scalette', kind: 'down', file: 'C_Scalette_REC.gpx' },
{ zone: 'canto', name: 'Uccellaia', kind: 'down', file: 'C_Uccellaia_REC.gpx' },
{ zone: 'canto', name: 'Zandona', kind: 'down', file: 'C_Zandona_REC.gpx' }
];

