/* mtbbergamo TRACKS */

/*
\u00E0 à
\u00E8 è
\u00EC ì
\u00F2 ò
\u00F9 ù
*/

var TRACKS = [
{ zone: 'maresana', name: '532, San Rocco', kind: 'down', file: 'M_532_REC.gpx', link: '2019/02/532' },
{ zone: 'maresana', name: '604 / Vertigo', kind: 'down', file: 'M_604_REC.gpx', link: '2018/11/604' },
{ zone: 'maresana', name: 'Bruna', kind: 'down', file: 'M_Bruna.gpx', link: '2018/11/bruna' },
{ zone: 'maresana', name: 'FarWest', kind: 'down', file: 'M_FarWest_REC.gpx', link: '2018/11/farwest' },
{ zone: 'maresana', name: '401 / Filoncino / Calvarola', kind: 'down', file: 'M_Filoncino_REC.gpx', link: '2018/11/401-filoncino' },
{ zone: 'maresana', name: 'Filone Easy', kind: 'down', file: 'M_FiloneEasy_REC.gpx', link: '2018/11/filone-easy' },
{ zone: 'maresana', name: '533 / Filone / Agostini', kind: 'down', file: 'M_Filone_REC.gpx', link:'2018/11/533-filone' },
{ zone: 'maresana', name: '533 / Veloce / Illegale', kind: 'down', file: 'M_Illegale_REC.gpx', link: '2018/11/533-illegale' },
{ zone: 'maresana', name: 'Rosciano', kind: 'down', file: 'M_Rosciano_REC.gpx', link: '2018/11/rosciano' },
{ zone: 'maresana', name: '402 / San Rocco', kind: 'down', file: 'M_SanRocco_REC.gpx', link: '2018/11/402-san-rocco' },
{ zone: 'maresana', name: '409 / Tornantini', kind: 'down', file: 'M_Tornantini_REC.gpx', link: '2018/11/tornantini' },
{ zone: 'maresana', name: 'Legnaia', kind: 'down', file: 'M_Legnaia_REC.gpx', link: '2018/11/legnaia' },
{ zone: 'maresana', name: 'Legnaia Variante Sud', kind: 'down', file: 'M_LegnaiaSud_VAR.gpx', link: '2018/11/legnaia' },
{ zone: 'maresana', name: 'Luca West', kind: 'down', file: 'M_LucaWest_REC.gpx', link: '2018/11/lucawest' },
{ zone: 'maresana, sorisole', name: '229', kind: 'down', file: 'M_229_REC.gpx', link: '2018/12/229' },
{ zone: 'maresana, sorisole', name: '229 Variante Premerlino', kind: 'down', file: 'M_229_Premerlino_VAR.gpx', link: '2018/12/229' },
{ zone: 'maresana', name: 'Birondina', kind: 'down', file: 'M_Birondina_REC.gpx', link:'2019/02/birondina' },
{ zone: 'maresana, seriana', name: '532A, Olera', kind: 'down', file: 'M_532A_Olera_REC.gpx', link:'2019/03/532a-olera' },
{ zone: 'maresana', name: 'Flying Dutchman', kind: 'down', file: 'M_FlyingDutchman_REC.gpx', link: '2019/01/flying-dutchman' },
{ zone: 'maresana', name: 'Trasferimento da Ca Del Lacc alla Forcella Del Sorriso', kind: 'up', file: 'M_CaDelLaccForcellaDelSorriso_REC.gpx', link: '2018/11/salite-maresana' },
{ zone: 'maresana', name: 'Trasferimento dal Castello della Moretta alla Maresana', kind: 'up', file: 'M_MorettaMaresana_REC.gpx', link: '2018/11/salite-maresana' },
{ zone: 'maresana, sorisole', name: 'Trasferimento da Premerlino a Ponteranica Alta', kind: 'up', file: 'M_PremerlinoPonteranicaAlta_REC.gpx', link: '2018/11/salite-maresana' },
{ zone: 'maresana', name: 'Salita da Ranica', kind: 'up', file: 'M_SalitaRanica_REC.gpx', link: '2018/11/salite-maresana' },
{ zone: 'maresana', name: 'Salita da Ponteranica', kind: 'up', file: 'M_SalitaPonteranica_REC.gpx', link: '2018/11/salite-maresana' },
{ zone: 'maresana', name: 'Salita da Ponteranica Alta', kind: 'up', file: 'M_SalitaPonteranicaAlta_REC.gpx', link: '2018/11/salite-maresana' },
{ zone: 'maresana', name: 'Salita da Olera', kind: 'up', file: 'M_SalitaOlera_REC.gpx', link: '2018/11/salite-maresana' },
{ zone: 'sorisole', name: 'Bacino', kind: 'down', file: 'SR_Bacino_REC.gpx' },
{ zone: 'sorisole', name: 'Pista Downhill', kind: 'down', file: 'SR_PistaDH_REC.gpx', link: '2018/12/pista-downhill' },
{ zone: 'sorisole', name: 'Galus\u00F9', kind: 'down', file: 'SR_Galusu_REC.gpx', link: '2018/12/galusu' },
{ zone: 'sorisole', name: 'Giongo', kind: 'down', file: 'SR_Giongo_REC.gpx' },
{ zone: 'sorisole', name: 'Salita alla Forcella di Rua', kind: 'up', file: 'SR_SalitaForcellaDiRua_REC.gpx' },
{ zone: 'sorisole', name: 'Salita al Galus\u00F9', kind: 'up', file: 'SR_SalitaGalusu_REC.gpx' },
{ zone: 'sorisole', name: 'Salita al Giongo', kind: 'up', file: 'SR_SalitaGiongo_REC.gpx' },
{ zone: 'sorisole', name: 'Trasferimento da Premerlino al Pisgi\u00F9', kind: 'up', file: 'SR_PremerlinoPisgiu_REC.gpx' },
{ zone: 'sorisole', name: 'Trasferimento alla Pista Downhill', kind: 'up', file: 'SR_203_REC.gpx' },
{ zone: 'imagna', name: 'Brumano, Passo Porta, Rota, Selino', kind: 'down', file: 'I_BrumanoPassoPortaRotaSelino_REC.gpx', link: '2018/12/brumano-passo-porta-rota-selino' },
{ zone: 'imagna', name: 'Ceresola, Roccoli Passata, Partigiano, Costa Cavallina, Clanezzo', kind: 'down', file: 'I_CeresolaRoccoliPassataPartigianoCostaCavallinaClanezzo_REC.gpx' },
{ zone: 'imagna', name: 'Palio, Canti, Tre Faggi', kind: 'down', file: 'I_PalioCantiTreFaggi_REC.gpx', link: '2018/12/palio-canti-tre-faggi' },
{ zone: 'imagna', name: 'Palio, Rifugio Resegone, Passo Porta, 575, Valsecca', kind: 'down', file: 'I_PalioRifugioResegonePassoPorta575Valsecca_REC.gpx' },
{ zone: 'imagna', name: 'Tre Faggi, 580, Locatello, Selino', kind: 'down', file: 'I_TreFaggi580LocatelloSelino_REC.gpx' },
{ zone: 'imagna', name: 'Tre Faggi, Corna, Blello, Selino Alto, Ponte Pietra', kind: 'down', file: 'I_TreFaggiCornaBlelloSelinoAltoPontePietra_REC.gpx', link: '2018/11/tra-faggi-corna-blello-selino-alto' },
{ zone: 'imagna', name: 'Trasferimento da Valsecca a Rota Imagna e a Locatello', kind: 'up', file: 'I_ValseccaRotaLocatello_REC.gpx', link: '2018/12/salite-imagna' },
{ zone: 'imagna', name: 'Ciclabile Valle Imagna', kind: 'up', file: 'I_CiclabileValleImagna_REC.gpx', link: '2018/12/salite-imagna' },
{ zone: 'imagna', name: 'Salita dalla Sbarra di Brumano al Palio', kind: 'up', file: 'I_SalitaSbarraPalio_REC.gpx', link: '2018/12/salite-imagna' },
{ zone: 'imagna', name: 'Salita da Selino a Fuipiano e ai Tre Faggi', kind: 'up', file: 'I_SalitaSelinoFuipianoTreFaggi_REC.gpx', link: '2018/12/salite-imagna' },
{ zone: 'imagna', name: 'Salita da Almenno a Costa Imagna e Valcava', kind: 'up', file: 'I_SalitaAlmennoCostaValcava_REC.gpx', link: '2018/12/salite-imagna' },
{ zone: 'imagna, valcava', name: 'Forcella Alta, 573, Mazzoleni, Selino', kind: 'down', file: 'I_ForcellaAlta573CostaMazzoleniSelino_REC.gpx' },
{ zone: 'imagna, valcava', name: 'Forcella Alta, 574, Valsecca, Selino', kind: 'down', file: 'I_ForcellaAlta574ValseccaSelino_REC.gpx' },
{ zone: 'imagna, valcava', name: 'Linzone Roncola Alta, Amagno', kind: 'down', file: 'I_LinzoneRoncolaAltaAmagno_REC.gpx' },
{ zone: 'martino, imagna, valcava', name: 'Linzone Roncola, Barlino', kind: 'down', file: 'I_LinzoneRoncolaBarlino_REC.gpx', link: '2018/11/linzone-roncola-barlino' },
{ zone: 'martino, imagna, valcava', name: 'Salita da Valcava al Linzone', kind: 'up', file: 'N_ValcavaLinzone_REC.gpx' },
{ zone: 'martino, valcava', name: 'Linzone, Monte Piacca, Baia, Spino, Palazzago', kind: 'down', file: 'N_LinzonePiaccaBaitaSpinoPalazzago_REC.gpx', link: '2018/11/linzone-monte-piacca-baita-burligo' },
{ zone: 'martino, valcava', name: 'Linzone, Monte Piacca, Spino, Ciacallo, Burligo', kind: 'down', file: 'N_LinzonePiaccaSpinoCiacallo807Burligo_REC.gpx', link: '2018/11/linzone-monte-piacca-baita-burligo' },
{ zone: 'martino, valcava', name: 'Valcava, Coldara, Colle Pedrino, Opreno, Burligo', kind: 'down', file: 'N_ValcavaColdaraPedrinoOprenoBurligo_REC.gpx', link: '2019/01/funivia-coldara-colle-pedrino-opreno' },
{ zone: 'martino, valcava', name: 'Valcava, Zuccherone, Coldara, Col Fopa, Opreno, Burligo', kind: 'down', file: 'N_ValcavaZuccheroneColdaraColFopaOprenoBurligo_REC.gpx', link: '2019/03/zuccherone-coldara-col-fopa-opreno' },
{ zone: 'martino, valcava', name: 'Valcava, 823, Colle di Sogno, Corna Martinella, Torre de Busi', kind: 'down', file: 'N_Valcava823SognoMartinellaClassicaFlow_REC.gpx', link: '2018/12/valcava-colle-di-sogno-corna-martinella' },
{ zone: 'martino, valcava', name: 'Forcella Alta, 817, Carenno', kind: 'down', file: 'N_ForcellaAlta817Carenno_REC.gpx', link: '2018/12/forcella-alta-817-carenno' },
{ zone: 'martino, valcava', name: 'Forcella Alta, 815, Carenno', kind: 'down', file: 'N_ForcellaAlta815Carenno_REC.gpx', link: '2019/01/forcella-alta-815-carenno' },
{ zone: 'martino, valcava', name: 'Forcella Alta, 812, Carenno', kind: 'down', file: 'N_ForcellaAlta812Carenno_REC.gpx', link: '2019/01/forcella-alta-812-carenno' },
{ zone: 'martino, valcava', name: 'Monte Tesoro, Direttissima, Colle Di Sogno, 823, 819, 822, Sopra Cornola', kind: 'down', file: 'N_TesoroDir823819822Sopra_REC.gpx', link: '2018/12/monte-tesoro-direttissima-colle-di' },
{ zone: 'martino, valcava', name: 'Salita da Torre De Busi a Valcava', kind: 'up', file: 'N_SalitaBusiValcava.gpx', link: '2018/12/salite-san-martino' },
{ zone: 'martino, valcava', name: 'Salita da Carenno alla Forcella Alta', kind: 'up', file: 'N_SalitaCarennoForcellaAlta_REC.gpx', link: '2018/12/salite-san-martino' },
{ zone: 'martino, valcava', name: 'Salita dalla Forcella Alta al Monte Tesoro', kind: 'up', file: 'N_SalitaForcellaAltaMonteTesoro_REC.gpx', link: '2018/12/salite-san-martino' },
{ zone: 'martino, valcava', name: 'Salita da Torre De Busi a Carenno', kind: 'up', file: 'N_SalitaBusiCarenno_REC.gpx', link: '2018/12/salite-san-martino' },
{ zone: 'martino, valcava', name: 'Salita da Palazzago alla Cava', kind: 'up', file: 'N_SalitaPalazzagoCava_REC.gpx', link: '2018/12/salite-san-martino' },
{ zone: 'martino, valcava', name: 'Salita da Carenno alla Corna Martinella', kind: 'up', file: 'N_SalitaCarennoMartinella_REC.gpx', link: '2018/12/salite-san-martino' },
{ zone: 'canto', name: 'Genestaro', kind: 'down', file: 'C_Genestaro_REC.gpx' },
{ zone: 'canto', name: 'Guendalina', kind: 'down', file: 'C_Guendalina_REC.gpx' },
{ zone: 'canto', name: 'Kompressor', kind: 'down', file: 'C_Kompressor_REC.gpx', link:'2019/02/kompressor' },
{ zone: 'canto', name: 'Pietra Sant Albero', kind: 'down', file: 'C_PietraSAlbero_REC.gpx' },
{ zone: 'canto', name: 'Rocce / Muschio / California / Lame Rotanti', kind: 'down', file: 'C_Rocce_REC.gpx', link:'2019/02/rocce-muschio' },
{ zone: 'canto', name: 'Scalette', kind: 'down', file: 'C_Scalette_REC.gpx', link:'2019/02/scalette' },
{ zone: 'canto', name: 'Uccellaia', kind: 'down', file: 'C_Uccellaia_REC.gpx', link:'2019/02/uccellaia' },
{ zone: 'canto', name: 'Zandona', kind: 'down', file: 'C_Zandona_REC.gpx', link:'2019/02/zandona' },
{ zone: 'canto', name: 'Salita da Sotto il Monte', kind: 'up', file: 'C_SalitaSottoIlMonte_REC.gpx', link:'2019/02/salite-monte-canto' },
{ zone: 'canto', name: 'Salita al Monte Canto', kind: 'up', file: 'C_SalitaMonteCanto_REC.gpx', link:'2019/02/salite-monte-canto' },
{ zone: 'canto', name: 'Salita da Pontida', kind: 'up', file: 'C_SalitaPontida_REC.gpx', link:'2019/02/salite-monte-canto' },
{ zone: 'canto', name: 'Salita da Ambivere', kind: 'up', file: 'C_SalitaAmbivere_REC.gpx', link:'2019/02/salite-monte-canto' },
{ zone: 'canto', name: 'Salita da Fontanella', kind: 'up', file: 'C_SalitaFontanella_REC.gpx', link:'2019/02/salite-monte-canto' },
{ zone: 'colli', name: '712 Nord', kind: 'down', file: 'PC_712Nord_REC.gpx', link: '2019/03/roccolone-nord' },
{ zone: 'colli', name: '712 Sud', kind: 'down', file: 'PC_712Sud_REC.gpx', link: '2019/01/roccolone-sud' },
{ zone: 'colli', name: '713 / Partigiano', kind: 'down', file: 'PC_713Partigiano_REC.gpx', link: '2019/03/roccolone-nord' },
{ zone: 'colli', name: 'Roccolo Nord', kind: 'down', file: 'PC_RoccoloNord_REC.gpx', link: '2019/03/roccolone-nord' },
{ zone: 'colli', name: '910 / Alpini', kind: 'down', file: 'PC_910_REC.gpx', link: '2018/12/910' },
{ zone: 'colli', name: 'Gussa Est', kind: 'down', file: 'PC_GussaEst_REC.gpx', link: '2019/01/monte-gussa' },
{ zone: 'colli', name: 'Gussa Nord', kind: 'down', file: 'PC_GussaNord_REC.gpx', link: '2019/01/monte-gussa' },
{ zone: 'colli', name: 'Gussa Ovest', kind: 'down', file: 'PC_GussaOvest_REC.gpx', link: '2019/01/monte-gussa' },
{ zone: 'colli', name: 'Gussa Sud', kind: 'down', file: 'PC_GussaSud_REC.gpx', link: '2019/01/monte-gussa' },
{ zone: 'colli', name: 'ExPistino', kind: 'down', file: 'PC_ExPistino_REC.gpx', link: '2019/03/roccolone-nord' },
{ zone: 'colli', name: 'Pistino Downhill', kind: 'down', file: 'PC_PistinoDownhill_REC.gpx', link: '2019/01/roccolone-sud' },
{ zone: 'colli', name: 'Roccolone', kind: 'down', file: 'PC_Roccolone_REC.gpx', link: '2018/12/roccolone' },
{ zone: 'colli', name: 'Roccolone Sud', kind: 'down', file: 'PC_RoccoloneSud_REC.gpx', link: '2019/01/roccolone-sud' },
{ zone: 'colli', name: 'Gradoni', kind: 'down', file: 'PC_Gradoni_REC.gpx', link: '2019/01/roccolone-sud' },
{ zone: 'colli', name: 'Allegrezza', kind: 'down', file: 'PC_Allegrezza_REC.gpx', link: '2018/12/allegrezza' },
{ zone: 'colli', name: 'Allegrezza Variante Sud', kind: 'down', file: 'PC_AllegrezzaSud_REC.gpx', link: '2018/12/allegrezza' },
{ zone: 'colli', name: 'Torre', kind: 'down', file: 'PC_Torre_REC.gpx', link: '2019/01/roccolone-sud' },
{ zone: 'colli', name: 'Salita da Astino', kind: 'up', file: 'PC_SalitaAstino_REC.gpx', link:'2018/12/salite-colli-bergamo' },
{ zone: 'colli', name: 'Salita al Monte Gussa', kind: 'up', file: 'PC_SalitaGussa_REC.gpx', link:'2018/12/salite-colli-bergamo' },
{ zone: 'colli', name: 'Salita dalla Madonna del Bosco', kind: 'up', file: 'PC_SalitaMadonnaDelBosco_REC.gpx', link:'2018/12/salite-colli-bergamo' },
{ zone: 'colli', name: 'Salita dal Roccolone', kind: 'up', file: 'PC_SalitaRoccolone_REC.gpx', link:'2018/12/salite-colli-bergamo' },
{ zone: 'seriana', name: 'Canto Basso, 533, Forcella del Sorriso', kind: 'down', file: 'S_CantoBassoForcellaSorriso_REC.gpx' },
{ zone: 'seriana', name: 'Cavlera, 528', kind: 'down', file: 'S_Cavlera528_REC.gpx' },
{ zone: 'seriana', name: 'Ganda, 520, Ganzzaniga', kind: 'down', file: 'S_Ganda520DHGazzaniga_REC.gpx' },
{ zone: 'seriana', name: 'Lonno, Val del Luio', kind: 'down', file: 'S_LonnoLuio_REC.gpx' },
{ zone: 'seriana', name: 'Monte Cavallo, Canto Basso', kind: 'down', file: 'S_MonteCavalloCantoBasso_REC.gpx' },
{ zone: 'seriana', name: 'Poieto, Gazzaniga', kind: 'down', file: 'S_PoietoGazzaniga_REC.gpx' },
{ zone: 'seriana', name: 'Lonno, Pizzo', kind: 'down', file: 'S_LonnoPizzo_REC.gpx' },
{ zone: 'seriana', name: 'Lonno, Percorso Vita', kind: 'down', file: 'S_LonnoPercorsoVita_REC.gpx' },
{ zone: 'seriana', name: 'Selvino, Lonno', kind: 'down', file: 'S_SelvinoLonno_REC.gpx' },
{ zone: 'seriana', name: 'Selvino, Mulattiera, Albino', kind: 'down', file: 'S_SelvinoMulattieraAlbino_REC.gpx' },
{ zone: 'seriana', name: 'Selvino, Purito, Trevasco', kind: 'down', file: 'S_SelvinoPuritoTrevasco_REC.gpx' },
{ zone: 'seriana', name: 'Selvino, Trote, Albino', kind: 'down', file: 'S_SelvinoTroteAlbino_REC.gpx' },
{ zone: 'seriana', name: 'Trasferimento da Castello di Nese, al Canto Basso', kind: 'up', file: 'S_CastelloNeseCantoBasso_REC.gpx' },
{ zone: 'seriana', name: 'Salita da Selvino al Poieto', kind: 'up', file: 'S_SalitaSelvinoPoieto_REC.gpx' },
{ zone: 'seriana', name: 'Salita da Vertova al Cavlera', kind: 'up', file: 'S_SalitaCavlera_REC.gpx' },
{ zone: 'seriana', name: 'Salita da Alzano a Lonno', kind: 'up', file: 'S_SalitaLonno_REC.gpx' },
{ zone: 'seriana', name: 'Salita da Nebro a Selvino', kind: 'up', file: 'S_SalitaNembroSelvino_REC.gpx' },
{ zone: 'seriana', name: 'Salita da Selvino a Ganda', kind: 'up', file: 'S_SalitaSelvinoGanda_REC.gpx' },
];

