/* mtbbergamo TRACKS */

var TRACKS = [
{ zone: 'maresana', name: '532', kind: 'down', file: 'M_532_REC.gpx' },
{ zone: 'maresana', name: '604', kind: 'down', file: 'M_604_REC.gpx', link: '2018/11/604' },
{ zone: 'maresana', name: 'Bruna', kind: 'down', file: 'M_Bruna.gpx', link: '2018/11/bruna' },
{ zone: 'maresana', name: 'FarWest', kind: 'down', file: 'M_FarWest_REC.gpx', link: '2018/11/farwest' },
{ zone: 'maresana', name: '401 / Filoncino', kind: 'down', file: 'M_Filoncino_REC.gpx', link: '2018/11/401-filoncino' },
{ zone: 'maresana', name: 'Filone Easy', kind: 'down', file: 'M_FiloneEasy_REC.gpx', link: '2018/11/filone-easy' },
{ zone: 'maresana', name: '533 / Filone', kind: 'down', file: 'M_Filone_REC.gpx', link:'2018/11/533-filone' },
{ zone: 'maresana', name: '533 / Illegale / Veloce', kind: 'down', file: 'M_Illegale_REC.gpx', link: '2018/11/533-illegale' },
{ zone: 'maresana', name: 'Rosciano', kind: 'down', file: 'M_Rosciano_REC.gpx', link: '2018/11/rosciano' },
{ zone: 'maresana', name: 'Salita da Ranica', kind: 'up', file: 'M_SalitaRanica_REC.gpx', link: '2018/11/salite-maresana' },
{ zone: 'maresana', name: 'Salita da Ponteranica', kind: 'up', file: 'M_SalitaPonteranica_REC.gpx', link: '2018/11/salite-maresana' },
{ zone: 'maresana', name: '402 / San Rocco', kind: 'down', file: 'M_SanRocco_REC.gpx', link: '2018/11/402-san-rocco' },
{ zone: 'maresana', name: '409 / Tornantini', kind: 'down', file: 'M_Tornantini_REC.gpx', link: '2018/11/tornantini' },
{ zone: 'maresana', name: 'Legnaia', kind: 'down', file: 'M_Legnaia_REC.gpx', link: '2018/11/legnaia' },
{ zone: 'maresana', name: 'Luca West', kind: 'down', file: 'M_LucaWest_REC.gpx', link: '2018/11/lucawest' },
{ zone: 'imagna', name: 'Brumano, Passo Porta, Rota, Selino', kind: 'down', file: 'T_BrumanoPassoPortaRotaSelino.gpx', link: '2018/12/brumano-passo-porta-rota-selino' },
{ zone: 'imagna', name: 'Ceresola, Roccoli Passata, Partigiano, Costa Cavallina, Clanezzo', kind: 'down', file: 'T_CeresolaRoccoliPassataPartigianoCostaCavallinaClanezzo.gpx' },
{ zone: 'imagna', name: 'Palio, Canti, Tre Faggi', kind: 'down', file: 'T_PalioCantiTreFaggi.gpx' },
{ zone: 'imagna', name: 'Palio, Rifugio Resegone, Passo Porta, 575, Valsecca', kind: 'down', file: 'T_PalioRifugioResegonePassoPorta575Valsecca.gpx' },
{ zone: 'imagna', name: 'Tre Faggi, 580, Locatello, Selino', kind: 'down', file: 'T_TreFaggi580LocatelloSelino.gpx' },
{ zone: 'imagna', name: 'Tre Faggi, Corna, Blello, Selino Alto, Ponte Pietra', kind: 'down', file: 'T_TreFaggiCornaBlelloSelinoAltoPontePietra.gpx', link: '2018/11/tra-faggi-corna-blello-selino-alto' },
{ zone: 'imagna', name: 'Salita dalla Sbarra di Brumana al Palio', kind: 'up', file: 'I_SalitaSbarraPalio_REC.gpx' },
{ zone: 'imagna', name: 'Salita da Selino a Fuipiano e ai Tre Faggi', kind: 'up', file: 'I_SalitaTreFaggi_REC.gpx' },
{ zone: 'imagna', name: 'Trasferimento da Valsecca a Rota Imagna e a Locatello', kind: 'up', file: 'I_ValseccaRotaLocatello_REC.gpx' },
{ zone: 'imagna, valcava', name: 'Forcella Alta, 573, Mazzoleni, Selino', kind: 'down', file: 'T_ForcellaAlta573CostaMazzoleniSelino.gpx' },
{ zone: 'imagna, valcava', name: 'Forcella Alta, 574, Valsecca, Selino', kind: 'down', file: 'T_ForcellaAlta574ValseccaSelino.gpx' },
{ zone: 'imagna, valcava', name: 'Linzone Roncola Alta, Amagno', kind: 'down', file: 'T_LinzoneRoncolaAltaAmagno.gpx' },
{ zone: 'imagna, valcava', name: 'Linzone Roncola, Barlino', kind: 'down', file: 'T_LinzoneRoncolaBarlino.gpx', link: '2018/11/linzone-roncola-barlino' },
{ zone: 'martino, valcava', name: 'Linzone, Monte Piacca, Baia, Spino, Burligo', kind: 'down', file: 'T_LinzonePiaccaBaitaSpinoBurligo.gpx', link: '2018/11/linzone-monte-piacca-baita-burligo' },
{ zone: 'martino, valcava', name: 'Valcava, Coldara, Colle Pedrino, Opreno, Burligo', kind: 'down', file: 'T_ValcavaColdaraPedrinoOprenoBurligo.gpx' },
{ zone: 'canto', name: 'Genestaro', kind: 'down', file: 'C_Genestaro_REC.gpx' },
{ zone: 'canto', name: 'Guendalina', kind: 'down', file: 'C_Guendalina_REC.gpx' } ,
{ zone: 'canto', name: 'Kompressor', kind: 'down', file: 'C_Kompressor_REC.gpx' },
{ zone: 'canto', name: 'Pietra Sant Albero', kind: 'down', file: 'C_PietraSAlbero_REC.gpx' },
{ zone: 'canto', name: 'Salita da Sotto il Monte', kind: 'up', file: 'C_SalitaSottoIlMonte_REC.gpx' },
{ zone: 'canto', name: 'Salita al Monte Canto', kind: 'up', file: 'C_SalitaMonteCanto_REC.gpx' },
{ zone: 'canto', name: 'Salita da Pontida', kind: 'up', file: 'C_SalitaPontida_REC.gpx' },
{ zone: 'canto', name: 'Salita da Ambivere', kind: 'up', file: 'C_SalitaAmbivere_REC.gpx' },
{ zone: 'canto', name: 'Scalette', kind: 'down', file: 'C_Scalette_REC.gpx' },
{ zone: 'canto', name: 'Uccellaia', kind: 'down', file: 'C_Uccellaia_REC.gpx' },
{ zone: 'canto', name: 'Zandona', kind: 'down', file: 'C_Zandona_REC.gpx' }
];

