#sh color_gopro.sh forcella_alta_panorama.mp4
#sh color_flat_fixed.sh forcella_alta_panorama_2.mp4
#sh color_gopro.sh roccolone_corto.mp4
#sh color_gopro.sh 712sud.mp4
#sh color_gopro.sh torre.mp4
#sh color_gopro.sh allegrezza.mp4
#sh color_ev0.sh tornantini.mp4
#sh color_gopro.sh 604.mp4
#sh color_gopro.sh 229.mp4
#sh color_gopro.sh pistadh.mp4
#sh color_gopro.sh collesogno.mp4
#sh color_gopro.sh tesoro.mp4
#sh color_gopro.sh 815.mp4
#sh color_flat_norm.sh farwest.mp4
#sh color_flat_norm.sh 812.mp4
#sh color_flat_stab.sh trefaggi_panorama.mp4
#sh color_flat_norm.sh trefaggi.mp4
#sh color_flat_norm.sh strada_per_blello_selino.mp4
#sh color_flat_norm.sh gussa_sud.mp4
#sh color_flat_norm.sh tornantini_passaggi.mp4
#sh color_flat_norm.sh filoncino_passaggi.mp4
#sh color_flat_norm.sh gussa_nord_parziale.mp4
#sh color_flat_norm.sh gussa_ovest.mp4
#sh color_flat_norm.sh allegrezza_sud.mp4
#sh color_flat_norm.sh linzone_piacca.mp4
#sh color_flat_norm.sh piacca_baita_palazzago.mp4
#sh color_flat_norm_native.sh linzone_panorama.mp4
sh color_flat_norm_native.sh valcava_funivia_coldara.mp4
#sh color_flat_norm_native.sh coldara_pedrino_opreno.mp4
#sh color_flat_norm_native.sh opreno_burligo.mp4
#sh color_flat_norm_native.sh filone_easy.mp4
#sh color_flat_norm_native.sh flying_dutchman.mp4

